// AUTO-GENERATED by scripts/generate-item-sets.mjs — do not edit by hand.
// Grand Exchange item sets and their components (exchange via a GE clerk's "Sets" option).
// 124 sets resolved from the wiki on 2026-07-03.

export interface ItemSetDef {
  setId: number;
  setName: string;
  pieces: { id: number; name: string }[];
}

export const ITEM_SETS: ItemSetDef[] = [
  {
    "setId": 13020,
    "setName": "Adamant gold-trimmed set (lg)",
    "pieces": [
      {
        "id": 2613,
        "name": "Adamant full helm (g)"
      },
      {
        "id": 2607,
        "name": "Adamant platebody (g)"
      },
      {
        "id": 2609,
        "name": "Adamant platelegs (g)"
      },
      {
        "id": 2611,
        "name": "Adamant kiteshield (g)"
      }
    ]
  },
  {
    "setId": 13022,
    "setName": "Adamant gold-trimmed set (sk)",
    "pieces": [
      {
        "id": 2613,
        "name": "Adamant full helm (g)"
      },
      {
        "id": 2607,
        "name": "Adamant platebody (g)"
      },
      {
        "id": 3475,
        "name": "Adamant plateskirt (g)"
      },
      {
        "id": 2611,
        "name": "Adamant kiteshield (g)"
      }
    ]
  },
  {
    "setId": 13012,
    "setName": "Adamant set (lg)",
    "pieces": [
      {
        "id": 1161,
        "name": "Adamant full helm"
      },
      {
        "id": 1123,
        "name": "Adamant platebody"
      },
      {
        "id": 1073,
        "name": "Adamant platelegs"
      },
      {
        "id": 1199,
        "name": "Adamant kiteshield"
      }
    ]
  },
  {
    "setId": 13014,
    "setName": "Adamant set (sk)",
    "pieces": [
      {
        "id": 1161,
        "name": "Adamant full helm"
      },
      {
        "id": 1123,
        "name": "Adamant platebody"
      },
      {
        "id": 1091,
        "name": "Adamant plateskirt"
      },
      {
        "id": 1199,
        "name": "Adamant kiteshield"
      }
    ]
  },
  {
    "setId": 13016,
    "setName": "Adamant trimmed set (lg)",
    "pieces": [
      {
        "id": 2605,
        "name": "Adamant full helm (t)"
      },
      {
        "id": 2599,
        "name": "Adamant platebody (t)"
      },
      {
        "id": 2601,
        "name": "Adamant platelegs (t)"
      },
      {
        "id": 2603,
        "name": "Adamant kiteshield (t)"
      }
    ]
  },
  {
    "setId": 13018,
    "setName": "Adamant trimmed set (sk)",
    "pieces": [
      {
        "id": 2605,
        "name": "Adamant full helm (t)"
      },
      {
        "id": 2599,
        "name": "Adamant platebody (t)"
      },
      {
        "id": 3474,
        "name": "Adamant plateskirt (t)"
      },
      {
        "id": 2603,
        "name": "Adamant kiteshield (t)"
      }
    ]
  },
  {
    "setId": 12881,
    "setName": "Ahrim's armour set",
    "pieces": [
      {
        "id": 4708,
        "name": "Ahrim's hood"
      },
      {
        "id": 4712,
        "name": "Ahrim's robetop"
      },
      {
        "id": 4714,
        "name": "Ahrim's robeskirt"
      },
      {
        "id": 4710,
        "name": "Ahrim's staff"
      }
    ]
  },
  {
    "setId": 21049,
    "setName": "Ancestral robes set",
    "pieces": [
      {
        "id": 21018,
        "name": "Ancestral hat"
      },
      {
        "id": 21021,
        "name": "Ancestral robe top"
      },
      {
        "id": 21024,
        "name": "Ancestral robe bottom"
      }
    ]
  },
  {
    "setId": 13171,
    "setName": "Ancient dragonhide set",
    "pieces": [
      {
        "id": 12496,
        "name": "Ancient coif"
      },
      {
        "id": 12492,
        "name": "Ancient d'hide body"
      },
      {
        "id": 12494,
        "name": "Ancient chaps"
      },
      {
        "id": 12490,
        "name": "Ancient bracers"
      }
    ]
  },
  {
    "setId": 13060,
    "setName": "Ancient rune armour set (lg)",
    "pieces": [
      {
        "id": 12466,
        "name": "Ancient full helm"
      },
      {
        "id": 12460,
        "name": "Ancient platebody"
      },
      {
        "id": 12462,
        "name": "Ancient platelegs"
      },
      {
        "id": 12468,
        "name": "Ancient kiteshield"
      }
    ]
  },
  {
    "setId": 13062,
    "setName": "Ancient rune armour set (sk)",
    "pieces": [
      {
        "id": 12466,
        "name": "Ancient full helm"
      },
      {
        "id": 12460,
        "name": "Ancient platebody"
      },
      {
        "id": 12464,
        "name": "Ancient plateskirt"
      },
      {
        "id": 12468,
        "name": "Ancient kiteshield"
      }
    ]
  },
  {
    "setId": 13169,
    "setName": "Armadyl dragonhide set",
    "pieces": [
      {
        "id": 12512,
        "name": "Armadyl coif"
      },
      {
        "id": 12508,
        "name": "Armadyl d'hide body"
      },
      {
        "id": 12510,
        "name": "Armadyl chaps"
      },
      {
        "id": 12506,
        "name": "Armadyl bracers"
      }
    ]
  },
  {
    "setId": 13052,
    "setName": "Armadyl rune armour set (lg)",
    "pieces": [
      {
        "id": 12476,
        "name": "Armadyl full helm"
      },
      {
        "id": 12470,
        "name": "Armadyl platebody"
      },
      {
        "id": 12472,
        "name": "Armadyl platelegs"
      },
      {
        "id": 12478,
        "name": "Armadyl kiteshield"
      }
    ]
  },
  {
    "setId": 13054,
    "setName": "Armadyl rune armour set (sk)",
    "pieces": [
      {
        "id": 12476,
        "name": "Armadyl full helm"
      },
      {
        "id": 12470,
        "name": "Armadyl platebody"
      },
      {
        "id": 12474,
        "name": "Armadyl plateskirt"
      },
      {
        "id": 12478,
        "name": "Armadyl kiteshield"
      }
    ]
  },
  {
    "setId": 13167,
    "setName": "Bandos dragonhide set",
    "pieces": [
      {
        "id": 12504,
        "name": "Bandos coif"
      },
      {
        "id": 12500,
        "name": "Bandos d'hide body"
      },
      {
        "id": 12502,
        "name": "Bandos chaps"
      },
      {
        "id": 12498,
        "name": "Bandos bracers"
      }
    ]
  },
  {
    "setId": 13056,
    "setName": "Bandos rune armour set (lg)",
    "pieces": [
      {
        "id": 12486,
        "name": "Bandos full helm"
      },
      {
        "id": 12480,
        "name": "Bandos platebody"
      },
      {
        "id": 12482,
        "name": "Bandos platelegs"
      },
      {
        "id": 12488,
        "name": "Bandos kiteshield"
      }
    ]
  },
  {
    "setId": 13058,
    "setName": "Bandos rune armour set (sk)",
    "pieces": [
      {
        "id": 12486,
        "name": "Bandos full helm"
      },
      {
        "id": 12480,
        "name": "Bandos platebody"
      },
      {
        "id": 12484,
        "name": "Bandos plateskirt"
      },
      {
        "id": 12488,
        "name": "Bandos kiteshield"
      }
    ]
  },
  {
    "setId": 12871,
    "setName": "Black dragonhide set",
    "pieces": [
      {
        "id": 2503,
        "name": "Black d'hide body"
      },
      {
        "id": 2497,
        "name": "Black d'hide chaps"
      },
      {
        "id": 2491,
        "name": "Black d'hide vambraces"
      }
    ]
  },
  {
    "setId": 12996,
    "setName": "Black gold-trimmed set (lg)",
    "pieces": [
      {
        "id": 2595,
        "name": "Black full helm (g)"
      },
      {
        "id": 2591,
        "name": "Black platebody (g)"
      },
      {
        "id": 2593,
        "name": "Black platelegs (g)"
      },
      {
        "id": 2597,
        "name": "Black kiteshield (g)"
      }
    ]
  },
  {
    "setId": 12998,
    "setName": "Black gold-trimmed set (sk)",
    "pieces": [
      {
        "id": 2595,
        "name": "Black full helm (g)"
      },
      {
        "id": 2591,
        "name": "Black platebody (g)"
      },
      {
        "id": 3473,
        "name": "Black plateskirt (g)"
      },
      {
        "id": 2597,
        "name": "Black kiteshield (g)"
      }
    ]
  },
  {
    "setId": 12988,
    "setName": "Black set (lg)",
    "pieces": [
      {
        "id": 1165,
        "name": "Black full helm"
      },
      {
        "id": 1125,
        "name": "Black platebody"
      },
      {
        "id": 1077,
        "name": "Black platelegs"
      },
      {
        "id": 1195,
        "name": "Black kiteshield"
      }
    ]
  },
  {
    "setId": 12990,
    "setName": "Black set (sk)",
    "pieces": [
      {
        "id": 1165,
        "name": "Black full helm"
      },
      {
        "id": 1125,
        "name": "Black platebody"
      },
      {
        "id": 1089,
        "name": "Black plateskirt"
      },
      {
        "id": 1195,
        "name": "Black kiteshield"
      }
    ]
  },
  {
    "setId": 12992,
    "setName": "Black trimmed set (lg)",
    "pieces": [
      {
        "id": 2587,
        "name": "Black full helm (t)"
      },
      {
        "id": 2583,
        "name": "Black platebody (t)"
      },
      {
        "id": 2585,
        "name": "Black platelegs (t)"
      },
      {
        "id": 2589,
        "name": "Black kiteshield (t)"
      }
    ]
  },
  {
    "setId": 12994,
    "setName": "Black trimmed set (sk)",
    "pieces": [
      {
        "id": 2587,
        "name": "Black full helm (t)"
      },
      {
        "id": 2583,
        "name": "Black platebody (t)"
      },
      {
        "id": 3472,
        "name": "Black plateskirt (t)"
      },
      {
        "id": 2589,
        "name": "Black kiteshield (t)"
      }
    ]
  },
  {
    "setId": 31136,
    "setName": "Blood moon armour set",
    "pieces": [
      {
        "id": 29028,
        "name": "Blood moon helm"
      },
      {
        "id": 29022,
        "name": "Blood moon chestplate"
      },
      {
        "id": 29025,
        "name": "Blood moon tassets"
      },
      {
        "id": 28997,
        "name": "Dual macuahuitl"
      }
    ]
  },
  {
    "setId": 31163,
    "setName": "Bloodbark armour set",
    "pieces": [
      {
        "id": 25413,
        "name": "Bloodbark helm"
      },
      {
        "id": 25404,
        "name": "Bloodbark body"
      },
      {
        "id": 25416,
        "name": "Bloodbark legs"
      },
      {
        "id": 25407,
        "name": "Bloodbark gauntlets"
      },
      {
        "id": 25410,
        "name": "Bloodbark boots"
      }
    ]
  },
  {
    "setId": 12867,
    "setName": "Blue dragonhide set",
    "pieces": [
      {
        "id": 2499,
        "name": "Blue d'hide body"
      },
      {
        "id": 2493,
        "name": "Blue d'hide chaps"
      },
      {
        "id": 2487,
        "name": "Blue d'hide vambraces"
      }
    ]
  },
  {
    "setId": 31139,
    "setName": "Blue moon armour set",
    "pieces": [
      {
        "id": 29019,
        "name": "Blue moon helm"
      },
      {
        "id": 29013,
        "name": "Blue moon chestplate"
      },
      {
        "id": 29016,
        "name": "Blue moon tassets"
      },
      {
        "id": 28988,
        "name": "Blue moon spear"
      }
    ]
  },
  {
    "setId": 13153,
    "setName": "Book of balance page set",
    "pieces": [
      {
        "id": 3835,
        "name": "Guthix page 1"
      },
      {
        "id": 3836,
        "name": "Guthix page 2"
      },
      {
        "id": 3837,
        "name": "Guthix page 3"
      },
      {
        "id": 3838,
        "name": "Guthix page 4"
      }
    ]
  },
  {
    "setId": 13159,
    "setName": "Book of darkness page set",
    "pieces": [
      {
        "id": 12621,
        "name": "Ancient page 1"
      },
      {
        "id": 12622,
        "name": "Ancient page 2"
      },
      {
        "id": 12623,
        "name": "Ancient page 3"
      },
      {
        "id": 12624,
        "name": "Ancient page 4"
      }
    ]
  },
  {
    "setId": 13157,
    "setName": "Book of law page set",
    "pieces": [
      {
        "id": 12617,
        "name": "Armadyl page 1"
      },
      {
        "id": 12618,
        "name": "Armadyl page 2"
      },
      {
        "id": 12619,
        "name": "Armadyl page 3"
      },
      {
        "id": 12620,
        "name": "Armadyl page 4"
      }
    ]
  },
  {
    "setId": 13155,
    "setName": "Book of war page set",
    "pieces": [
      {
        "id": 12613,
        "name": "Bandos page 1"
      },
      {
        "id": 12614,
        "name": "Bandos page 2"
      },
      {
        "id": 12615,
        "name": "Bandos page 3"
      },
      {
        "id": 12616,
        "name": "Bandos page 4"
      }
    ]
  },
  {
    "setId": 12968,
    "setName": "Bronze gold-trimmed set (lg)",
    "pieces": [
      {
        "id": 12211,
        "name": "Bronze full helm (g)"
      },
      {
        "id": 12205,
        "name": "Bronze platebody (g)"
      },
      {
        "id": 12207,
        "name": "Bronze platelegs (g)"
      },
      {
        "id": 12213,
        "name": "Bronze kiteshield (g)"
      }
    ]
  },
  {
    "setId": 12970,
    "setName": "Bronze gold-trimmed set (sk)",
    "pieces": [
      {
        "id": 12211,
        "name": "Bronze full helm (g)"
      },
      {
        "id": 12205,
        "name": "Bronze platebody (g)"
      },
      {
        "id": 12209,
        "name": "Bronze plateskirt (g)"
      },
      {
        "id": 12213,
        "name": "Bronze kiteshield (g)"
      }
    ]
  },
  {
    "setId": 12960,
    "setName": "Bronze set (lg)",
    "pieces": [
      {
        "id": 1155,
        "name": "Bronze full helm"
      },
      {
        "id": 1117,
        "name": "Bronze platebody"
      },
      {
        "id": 1075,
        "name": "Bronze platelegs"
      },
      {
        "id": 1189,
        "name": "Bronze kiteshield"
      }
    ]
  },
  {
    "setId": 12962,
    "setName": "Bronze set (sk)",
    "pieces": [
      {
        "id": 1155,
        "name": "Bronze full helm"
      },
      {
        "id": 1117,
        "name": "Bronze platebody"
      },
      {
        "id": 1087,
        "name": "Bronze plateskirt"
      },
      {
        "id": 1189,
        "name": "Bronze kiteshield"
      }
    ]
  },
  {
    "setId": 12964,
    "setName": "Bronze trimmed set (lg)",
    "pieces": [
      {
        "id": 12221,
        "name": "Bronze full helm (t)"
      },
      {
        "id": 12215,
        "name": "Bronze platebody (t)"
      },
      {
        "id": 12217,
        "name": "Bronze platelegs (t)"
      },
      {
        "id": 12223,
        "name": "Bronze kiteshield (t)"
      }
    ]
  },
  {
    "setId": 12966,
    "setName": "Bronze trimmed set (sk)",
    "pieces": [
      {
        "id": 12221,
        "name": "Bronze full helm (t)"
      },
      {
        "id": 12215,
        "name": "Bronze platebody (t)"
      },
      {
        "id": 12219,
        "name": "Bronze plateskirt (t)"
      },
      {
        "id": 12223,
        "name": "Bronze kiteshield (t)"
      }
    ]
  },
  {
    "setId": 13064,
    "setName": "Combat potion set",
    "pieces": [
      {
        "id": 2428,
        "name": "Attack potion(4)"
      },
      {
        "id": 113,
        "name": "Strength potion(4)"
      },
      {
        "id": 2432,
        "name": "Defence potion(4)"
      }
    ]
  },
  {
    "setId": 24333,
    "setName": "Dagon'hai robes set",
    "pieces": [
      {
        "id": 24288,
        "name": "Dagon'hai hat"
      },
      {
        "id": 24291,
        "name": "Dagon'hai robe top"
      },
      {
        "id": 24294,
        "name": "Dagon'hai robe bottom"
      }
    ]
  },
  {
    "setId": 33451,
    "setName": "Demonic pacts relic hunter (t1) armour set",
    "pieces": [
      {
        "id": 33260,
        "name": "Demonic hood (t1)"
      },
      {
        "id": 33263,
        "name": "Demonic robe top (t1)"
      },
      {
        "id": 33266,
        "name": "Demonic robe bottom (t1)"
      },
      {
        "id": 33269,
        "name": "Demonic boots (t1)"
      }
    ]
  },
  {
    "setId": 33454,
    "setName": "Demonic pacts relic hunter (t2) armour set",
    "pieces": [
      {
        "id": 33272,
        "name": "Demonic hood (t2)"
      },
      {
        "id": 33275,
        "name": "Demonic robe top (t2)"
      },
      {
        "id": 33278,
        "name": "Demonic robe bottom (t2)"
      },
      {
        "id": 33281,
        "name": "Demonic boots (t2)"
      }
    ]
  },
  {
    "setId": 33457,
    "setName": "Demonic pacts relic hunter (t3) armour set",
    "pieces": [
      {
        "id": 33284,
        "name": "Demonic hood (t3)"
      },
      {
        "id": 33287,
        "name": "Demonic robe top (t3)"
      },
      {
        "id": 33290,
        "name": "Demonic robe bottom (t3)"
      },
      {
        "id": 33293,
        "name": "Demonic boots (t3)"
      }
    ]
  },
  {
    "setId": 12877,
    "setName": "Dharok's armour set",
    "pieces": [
      {
        "id": 4716,
        "name": "Dharok's helm"
      },
      {
        "id": 4720,
        "name": "Dharok's platebody"
      },
      {
        "id": 4722,
        "name": "Dharok's platelegs"
      },
      {
        "id": 4718,
        "name": "Dharok's greataxe"
      }
    ]
  },
  {
    "setId": 21882,
    "setName": "Dragon armour set (lg)",
    "pieces": [
      {
        "id": 11335,
        "name": "Dragon full helm"
      },
      {
        "id": 21892,
        "name": "Dragon platebody"
      },
      {
        "id": 4087,
        "name": "Dragon platelegs"
      },
      {
        "id": 21895,
        "name": "Dragon kiteshield"
      }
    ]
  },
  {
    "setId": 21885,
    "setName": "Dragon armour set (sk)",
    "pieces": [
      {
        "id": 11335,
        "name": "Dragon full helm"
      },
      {
        "id": 21892,
        "name": "Dragon platebody"
      },
      {
        "id": 4585,
        "name": "Dragon plateskirt"
      },
      {
        "id": 21895,
        "name": "Dragon kiteshield"
      }
    ]
  },
  {
    "setId": 23667,
    "setName": "Dragonstone armour set",
    "pieces": [
      {
        "id": 24034,
        "name": "Dragonstone full helm"
      },
      {
        "id": 24037,
        "name": "Dragonstone platebody"
      },
      {
        "id": 24040,
        "name": "Dragonstone platelegs"
      },
      {
        "id": 24046,
        "name": "Dragonstone gauntlets"
      },
      {
        "id": 24043,
        "name": "Dragonstone boots"
      }
    ]
  },
  {
    "setId": 12863,
    "setName": "Dwarf cannon set",
    "pieces": [
      {
        "id": 10,
        "name": "Cannon barrels"
      },
      {
        "id": 6,
        "name": "Cannon base"
      },
      {
        "id": 12,
        "name": "Cannon furnace"
      },
      {
        "id": 8,
        "name": "Cannon stand"
      }
    ]
  },
  {
    "setId": 31142,
    "setName": "Eclipse moon armour set",
    "pieces": [
      {
        "id": 29010,
        "name": "Eclipse moon helm"
      },
      {
        "id": 29004,
        "name": "Eclipse moon chestplate"
      },
      {
        "id": 29007,
        "name": "Eclipse moon tassets"
      },
      {
        "id": 29000,
        "name": "Eclipse atlatl"
      }
    ]
  },
  {
    "setId": 13036,
    "setName": "Gilded armour set (lg)",
    "pieces": [
      {
        "id": 3486,
        "name": "Gilded full helm"
      },
      {
        "id": 3481,
        "name": "Gilded platebody"
      },
      {
        "id": 3483,
        "name": "Gilded platelegs"
      },
      {
        "id": 3488,
        "name": "Gilded kiteshield"
      }
    ]
  },
  {
    "setId": 13038,
    "setName": "Gilded armour set (sk)",
    "pieces": [
      {
        "id": 3486,
        "name": "Gilded full helm"
      },
      {
        "id": 3481,
        "name": "Gilded platebody"
      },
      {
        "id": 3485,
        "name": "Gilded plateskirt"
      },
      {
        "id": 3488,
        "name": "Gilded kiteshield"
      }
    ]
  },
  {
    "setId": 23124,
    "setName": "Gilded dragonhide set",
    "pieces": [
      {
        "id": 23264,
        "name": "Gilded d'hide body"
      },
      {
        "id": 23267,
        "name": "Gilded d'hide chaps"
      },
      {
        "id": 23261,
        "name": "Gilded d'hide vambraces"
      }
    ]
  },
  {
    "setId": 12865,
    "setName": "Green dragonhide set",
    "pieces": [
      {
        "id": 1135,
        "name": "Green d'hide body"
      },
      {
        "id": 1099,
        "name": "Green d'hide chaps"
      },
      {
        "id": 1065,
        "name": "Green d'hide vambraces"
      }
    ]
  },
  {
    "setId": 12873,
    "setName": "Guthan's armour set",
    "pieces": [
      {
        "id": 4724,
        "name": "Guthan's helm"
      },
      {
        "id": 4728,
        "name": "Guthan's platebody"
      },
      {
        "id": 4730,
        "name": "Guthan's chainskirt"
      },
      {
        "id": 4726,
        "name": "Guthan's warspear"
      }
    ]
  },
  {
    "setId": 13048,
    "setName": "Guthix armour set (lg)",
    "pieces": [
      {
        "id": 2673,
        "name": "Guthix full helm"
      },
      {
        "id": 2669,
        "name": "Guthix platebody"
      },
      {
        "id": 2671,
        "name": "Guthix platelegs"
      },
      {
        "id": 2675,
        "name": "Guthix kiteshield"
      }
    ]
  },
  {
    "setId": 13050,
    "setName": "Guthix armour set (sk)",
    "pieces": [
      {
        "id": 2673,
        "name": "Guthix full helm"
      },
      {
        "id": 2669,
        "name": "Guthix platebody"
      },
      {
        "id": 3480,
        "name": "Guthix plateskirt"
      },
      {
        "id": 2675,
        "name": "Guthix kiteshield"
      }
    ]
  },
  {
    "setId": 13165,
    "setName": "Guthix dragonhide set",
    "pieces": [
      {
        "id": 10382,
        "name": "Guthix coif"
      },
      {
        "id": 10378,
        "name": "Guthix d'hide body"
      },
      {
        "id": 10380,
        "name": "Guthix chaps"
      },
      {
        "id": 10376,
        "name": "Guthix bracers"
      }
    ]
  },
  {
    "setId": 13175,
    "setName": "Halloween mask set",
    "pieces": [
      {
        "id": 1057,
        "name": "Red halloween mask"
      },
      {
        "id": 1053,
        "name": "Green halloween mask"
      },
      {
        "id": 1055,
        "name": "Blue halloween mask"
      }
    ]
  },
  {
    "setId": 13149,
    "setName": "Holy book page set",
    "pieces": [
      {
        "id": 3827,
        "name": "Saradomin page 1"
      },
      {
        "id": 3828,
        "name": "Saradomin page 2"
      },
      {
        "id": 3829,
        "name": "Saradomin page 3"
      },
      {
        "id": 3830,
        "name": "Saradomin page 4"
      }
    ]
  },
  {
    "setId": 31169,
    "setName": "Hueycoatl hide armour set",
    "pieces": [
      {
        "id": 30073,
        "name": "Hueycoatl hide coif"
      },
      {
        "id": 30076,
        "name": "Hueycoatl hide body"
      },
      {
        "id": 30079,
        "name": "Hueycoatl hide chaps"
      },
      {
        "id": 30082,
        "name": "Hueycoatl hide vambraces"
      }
    ]
  },
  {
    "setId": 24488,
    "setName": "Inquisitor's armour set",
    "pieces": [
      {
        "id": 24419,
        "name": "Inquisitor's great helm"
      },
      {
        "id": 24420,
        "name": "Inquisitor's hauberk"
      },
      {
        "id": 24421,
        "name": "Inquisitor's plateskirt"
      }
    ]
  },
  {
    "setId": 12980,
    "setName": "Iron gold-trimmed set (lg)",
    "pieces": [
      {
        "id": 12241,
        "name": "Iron full helm (g)"
      },
      {
        "id": 12235,
        "name": "Iron platebody (g)"
      },
      {
        "id": 12237,
        "name": "Iron platelegs (g)"
      },
      {
        "id": 12243,
        "name": "Iron kiteshield (g)"
      }
    ]
  },
  {
    "setId": 12982,
    "setName": "Iron gold-trimmed set (sk)",
    "pieces": [
      {
        "id": 12241,
        "name": "Iron full helm (g)"
      },
      {
        "id": 12235,
        "name": "Iron platebody (g)"
      },
      {
        "id": 12239,
        "name": "Iron plateskirt (g)"
      },
      {
        "id": 12243,
        "name": "Iron kiteshield (g)"
      }
    ]
  },
  {
    "setId": 12972,
    "setName": "Iron set (lg)",
    "pieces": [
      {
        "id": 1153,
        "name": "Iron full helm"
      },
      {
        "id": 1115,
        "name": "Iron platebody"
      },
      {
        "id": 1067,
        "name": "Iron platelegs"
      },
      {
        "id": 1191,
        "name": "Iron kiteshield"
      }
    ]
  },
  {
    "setId": 12974,
    "setName": "Iron set (sk)",
    "pieces": [
      {
        "id": 1153,
        "name": "Iron full helm"
      },
      {
        "id": 1115,
        "name": "Iron platebody"
      },
      {
        "id": 1081,
        "name": "Iron plateskirt"
      },
      {
        "id": 1191,
        "name": "Iron kiteshield"
      }
    ]
  },
  {
    "setId": 12976,
    "setName": "Iron trimmed set (lg)",
    "pieces": [
      {
        "id": 12231,
        "name": "Iron full helm (t)"
      },
      {
        "id": 12225,
        "name": "Iron platebody (t)"
      },
      {
        "id": 12227,
        "name": "Iron platelegs (t)"
      },
      {
        "id": 12233,
        "name": "Iron kiteshield (t)"
      }
    ]
  },
  {
    "setId": 12978,
    "setName": "Iron trimmed set (sk)",
    "pieces": [
      {
        "id": 12231,
        "name": "Iron full helm (t)"
      },
      {
        "id": 12225,
        "name": "Iron platebody (t)"
      },
      {
        "id": 12229,
        "name": "Iron plateskirt (t)"
      },
      {
        "id": 12233,
        "name": "Iron kiteshield (t)"
      }
    ]
  },
  {
    "setId": 22438,
    "setName": "Justiciar armour set",
    "pieces": [
      {
        "id": 22326,
        "name": "Justiciar faceguard"
      },
      {
        "id": 22327,
        "name": "Justiciar chestguard"
      },
      {
        "id": 22328,
        "name": "Justiciar legguards"
      }
    ]
  },
  {
    "setId": 12883,
    "setName": "Karil's armour set",
    "pieces": [
      {
        "id": 4732,
        "name": "Karil's coif"
      },
      {
        "id": 4736,
        "name": "Karil's leathertop"
      },
      {
        "id": 4738,
        "name": "Karil's leatherskirt"
      },
      {
        "id": 4734,
        "name": "Karil's crossbow"
      }
    ]
  },
  {
    "setId": 13008,
    "setName": "Mithril gold-trimmed set (lg)",
    "pieces": [
      {
        "id": 12283,
        "name": "Mithril full helm (g)"
      },
      {
        "id": 12277,
        "name": "Mithril platebody (g)"
      },
      {
        "id": 12279,
        "name": "Mithril platelegs (g)"
      },
      {
        "id": 12281,
        "name": "Mithril kiteshield (g)"
      }
    ]
  },
  {
    "setId": 13010,
    "setName": "Mithril gold-trimmed set (sk)",
    "pieces": [
      {
        "id": 12283,
        "name": "Mithril full helm (g)"
      },
      {
        "id": 12277,
        "name": "Mithril platebody (g)"
      },
      {
        "id": 12285,
        "name": "Mithril plateskirt (g)"
      },
      {
        "id": 12281,
        "name": "Mithril kiteshield (g)"
      }
    ]
  },
  {
    "setId": 13000,
    "setName": "Mithril set (lg)",
    "pieces": [
      {
        "id": 1159,
        "name": "Mithril full helm"
      },
      {
        "id": 1121,
        "name": "Mithril platebody"
      },
      {
        "id": 1071,
        "name": "Mithril platelegs"
      },
      {
        "id": 1197,
        "name": "Mithril kiteshield"
      }
    ]
  },
  {
    "setId": 13002,
    "setName": "Mithril set (sk)",
    "pieces": [
      {
        "id": 1159,
        "name": "Mithril full helm"
      },
      {
        "id": 1121,
        "name": "Mithril platebody"
      },
      {
        "id": 1085,
        "name": "Mithril plateskirt"
      },
      {
        "id": 1197,
        "name": "Mithril kiteshield"
      }
    ]
  },
  {
    "setId": 13004,
    "setName": "Mithril trimmed set (lg)",
    "pieces": [
      {
        "id": 12293,
        "name": "Mithril full helm (t)"
      },
      {
        "id": 12287,
        "name": "Mithril platebody (t)"
      },
      {
        "id": 12289,
        "name": "Mithril platelegs (t)"
      },
      {
        "id": 12291,
        "name": "Mithril kiteshield (t)"
      }
    ]
  },
  {
    "setId": 13006,
    "setName": "Mithril trimmed set (sk)",
    "pieces": [
      {
        "id": 12293,
        "name": "Mithril full helm (t)"
      },
      {
        "id": 12287,
        "name": "Mithril platebody (t)"
      },
      {
        "id": 12295,
        "name": "Mithril plateskirt (t)"
      },
      {
        "id": 12291,
        "name": "Mithril kiteshield (t)"
      }
    ]
  },
  {
    "setId": 31166,
    "setName": "Mixed hide armour set",
    "pieces": [
      {
        "id": 29280,
        "name": "Mixed hide top"
      },
      {
        "id": 29283,
        "name": "Mixed hide legs"
      },
      {
        "id": 29286,
        "name": "Mixed hide boots"
      },
      {
        "id": 29289,
        "name": "Mixed hide cape"
      }
    ]
  },
  {
    "setId": 30744,
    "setName": "Oathplate armour set",
    "pieces": [
      {
        "id": 30750,
        "name": "Oathplate helm"
      },
      {
        "id": 30753,
        "name": "Oathplate chest"
      },
      {
        "id": 30756,
        "name": "Oathplate legs"
      }
    ]
  },
  {
    "setId": 21279,
    "setName": "Obsidian armour set",
    "pieces": [
      {
        "id": 21298,
        "name": "Obsidian helmet"
      },
      {
        "id": 21301,
        "name": "Obsidian platebody"
      },
      {
        "id": 21304,
        "name": "Obsidian platelegs"
      }
    ]
  },
  {
    "setId": 13173,
    "setName": "Partyhat set",
    "pieces": [
      {
        "id": 1038,
        "name": "Red partyhat"
      },
      {
        "id": 1040,
        "name": "Yellow partyhat"
      },
      {
        "id": 1044,
        "name": "Green partyhat"
      },
      {
        "id": 1042,
        "name": "Blue partyhat"
      },
      {
        "id": 1046,
        "name": "Purple partyhat"
      },
      {
        "id": 1048,
        "name": "White partyhat"
      }
    ]
  },
  {
    "setId": 30331,
    "setName": "Raging echoes relic hunter (t1) armour set",
    "pieces": [
      {
        "id": 30404,
        "name": "Raging echoes hat (t1)"
      },
      {
        "id": 30406,
        "name": "Raging echoes top (t1)"
      },
      {
        "id": 30408,
        "name": "Raging echoes robeskirt (t1)"
      },
      {
        "id": 30410,
        "name": "Raging echoes boots (t1)"
      }
    ]
  },
  {
    "setId": 30334,
    "setName": "Raging echoes relic hunter (t2) armour set",
    "pieces": [
      {
        "id": 30412,
        "name": "Raging echoes hat (t2)"
      },
      {
        "id": 30414,
        "name": "Raging echoes top (t2)"
      },
      {
        "id": 30416,
        "name": "Raging echoes robeskirt (t2)"
      },
      {
        "id": 30418,
        "name": "Raging echoes boots (t2)"
      }
    ]
  },
  {
    "setId": 30337,
    "setName": "Raging echoes relic hunter (t3) armour set",
    "pieces": [
      {
        "id": 30420,
        "name": "Raging echoes hat (t3)"
      },
      {
        "id": 30422,
        "name": "Raging echoes top (t3)"
      },
      {
        "id": 30424,
        "name": "Raging echoes robeskirt (t3)"
      },
      {
        "id": 30426,
        "name": "Raging echoes boots (t3)"
      }
    ]
  },
  {
    "setId": 12869,
    "setName": "Red dragonhide set",
    "pieces": [
      {
        "id": 2501,
        "name": "Red d'hide body"
      },
      {
        "id": 2495,
        "name": "Red d'hide chaps"
      },
      {
        "id": 2489,
        "name": "Red d'hide vambraces"
      }
    ]
  },
  {
    "setId": 31151,
    "setName": "Rock-shell armour set",
    "pieces": [
      {
        "id": 6128,
        "name": "Rock-shell helm"
      },
      {
        "id": 6129,
        "name": "Rock-shell plate"
      },
      {
        "id": 6130,
        "name": "Rock-shell legs"
      },
      {
        "id": 6151,
        "name": "Rock-shell gloves"
      },
      {
        "id": 6145,
        "name": "Rock-shell boots"
      }
    ]
  },
  {
    "setId": 13024,
    "setName": "Rune armour set (lg)",
    "pieces": [
      {
        "id": 1163,
        "name": "Rune full helm"
      },
      {
        "id": 1127,
        "name": "Rune platebody"
      },
      {
        "id": 1079,
        "name": "Rune platelegs"
      },
      {
        "id": 1201,
        "name": "Rune kiteshield"
      }
    ]
  },
  {
    "setId": 13026,
    "setName": "Rune armour set (sk)",
    "pieces": [
      {
        "id": 1163,
        "name": "Rune full helm"
      },
      {
        "id": 1127,
        "name": "Rune platebody"
      },
      {
        "id": 1093,
        "name": "Rune plateskirt"
      },
      {
        "id": 1201,
        "name": "Rune kiteshield"
      }
    ]
  },
  {
    "setId": 13032,
    "setName": "Rune gold-trimmed set (lg)",
    "pieces": [
      {
        "id": 2619,
        "name": "Rune full helm (g)"
      },
      {
        "id": 2615,
        "name": "Rune platebody (g)"
      },
      {
        "id": 2617,
        "name": "Rune platelegs (g)"
      },
      {
        "id": 2621,
        "name": "Rune kiteshield (g)"
      }
    ]
  },
  {
    "setId": 13034,
    "setName": "Rune gold-trimmed set (sk)",
    "pieces": [
      {
        "id": 2619,
        "name": "Rune full helm (g)"
      },
      {
        "id": 2615,
        "name": "Rune platebody (g)"
      },
      {
        "id": 3476,
        "name": "Rune plateskirt (g)"
      },
      {
        "id": 2621,
        "name": "Rune kiteshield (g)"
      }
    ]
  },
  {
    "setId": 13028,
    "setName": "Rune trimmed set (lg)",
    "pieces": [
      {
        "id": 2627,
        "name": "Rune full helm (t)"
      },
      {
        "id": 2623,
        "name": "Rune platebody (t)"
      },
      {
        "id": 2625,
        "name": "Rune platelegs (t)"
      },
      {
        "id": 2629,
        "name": "Rune kiteshield (t)"
      }
    ]
  },
  {
    "setId": 13030,
    "setName": "Rune trimmed set (sk)",
    "pieces": [
      {
        "id": 2627,
        "name": "Rune full helm (t)"
      },
      {
        "id": 2623,
        "name": "Rune platebody (t)"
      },
      {
        "id": 3477,
        "name": "Rune plateskirt (t)"
      },
      {
        "id": 2629,
        "name": "Rune kiteshield (t)"
      }
    ]
  },
  {
    "setId": 13040,
    "setName": "Saradomin armour set (lg)",
    "pieces": [
      {
        "id": 2665,
        "name": "Saradomin full helm"
      },
      {
        "id": 2661,
        "name": "Saradomin platebody"
      },
      {
        "id": 2663,
        "name": "Saradomin platelegs"
      },
      {
        "id": 2667,
        "name": "Saradomin kiteshield"
      }
    ]
  },
  {
    "setId": 13042,
    "setName": "Saradomin armour set (sk)",
    "pieces": [
      {
        "id": 2665,
        "name": "Saradomin full helm"
      },
      {
        "id": 2661,
        "name": "Saradomin platebody"
      },
      {
        "id": 3479,
        "name": "Saradomin plateskirt"
      },
      {
        "id": 2667,
        "name": "Saradomin kiteshield"
      }
    ]
  },
  {
    "setId": 13163,
    "setName": "Saradomin dragonhide set",
    "pieces": [
      {
        "id": 10390,
        "name": "Saradomin coif"
      },
      {
        "id": 10386,
        "name": "Saradomin d'hide body"
      },
      {
        "id": 10388,
        "name": "Saradomin chaps"
      },
      {
        "id": 10384,
        "name": "Saradomin bracers"
      }
    ]
  },
  {
    "setId": 26554,
    "setName": "Shattered relic hunter (t1) armour set",
    "pieces": [
      {
        "id": 26427,
        "name": "Shattered hood (t1)"
      },
      {
        "id": 26430,
        "name": "Shattered top (t1)"
      },
      {
        "id": 26433,
        "name": "Shattered trousers (t1)"
      },
      {
        "id": 26436,
        "name": "Shattered boots (t1)"
      }
    ]
  },
  {
    "setId": 26557,
    "setName": "Shattered relic hunter (t2) armour set",
    "pieces": [
      {
        "id": 26439,
        "name": "Shattered hood (t2)"
      },
      {
        "id": 26442,
        "name": "Shattered top (t2)"
      },
      {
        "id": 26445,
        "name": "Shattered trousers (t2)"
      },
      {
        "id": 26448,
        "name": "Shattered boots (t2)"
      }
    ]
  },
  {
    "setId": 26560,
    "setName": "Shattered relic hunter (t3) armour set",
    "pieces": [
      {
        "id": 26451,
        "name": "Shattered hood (t3)"
      },
      {
        "id": 26454,
        "name": "Shattered top (t3)"
      },
      {
        "id": 26457,
        "name": "Shattered trousers (t3)"
      },
      {
        "id": 26460,
        "name": "Shattered boots (t3)"
      }
    ]
  },
  {
    "setId": 31154,
    "setName": "Skeletal armour set",
    "pieces": [
      {
        "id": 6137,
        "name": "Skeletal helm"
      },
      {
        "id": 6139,
        "name": "Skeletal top"
      },
      {
        "id": 6141,
        "name": "Skeletal bottoms"
      },
      {
        "id": 6153,
        "name": "Skeletal gloves"
      },
      {
        "id": 6147,
        "name": "Skeletal boots"
      }
    ]
  },
  {
    "setId": 31157,
    "setName": "Spined armour set",
    "pieces": [
      {
        "id": 6131,
        "name": "Spined helm"
      },
      {
        "id": 6133,
        "name": "Spined body"
      },
      {
        "id": 6135,
        "name": "Spined chaps"
      },
      {
        "id": 6149,
        "name": "Spined gloves"
      },
      {
        "id": 6143,
        "name": "Spined boots"
      }
    ]
  },
  {
    "setId": 20382,
    "setName": "Steel gold-trimmed set (lg)",
    "pieces": [
      {
        "id": 20178,
        "name": "Steel full helm (g)"
      },
      {
        "id": 20169,
        "name": "Steel platebody (g)"
      },
      {
        "id": 20172,
        "name": "Steel platelegs (g)"
      },
      {
        "id": 20181,
        "name": "Steel kiteshield (g)"
      }
    ]
  },
  {
    "setId": 20385,
    "setName": "Steel gold-trimmed set (sk)",
    "pieces": [
      {
        "id": 20178,
        "name": "Steel full helm (g)"
      },
      {
        "id": 20169,
        "name": "Steel platebody (g)"
      },
      {
        "id": 20175,
        "name": "Steel plateskirt (g)"
      },
      {
        "id": 20181,
        "name": "Steel kiteshield (g)"
      }
    ]
  },
  {
    "setId": 12984,
    "setName": "Steel set (lg)",
    "pieces": [
      {
        "id": 1157,
        "name": "Steel full helm"
      },
      {
        "id": 1119,
        "name": "Steel platebody"
      },
      {
        "id": 1069,
        "name": "Steel platelegs"
      },
      {
        "id": 1193,
        "name": "Steel kiteshield"
      }
    ]
  },
  {
    "setId": 12986,
    "setName": "Steel set (sk)",
    "pieces": [
      {
        "id": 1157,
        "name": "Steel full helm"
      },
      {
        "id": 1119,
        "name": "Steel platebody"
      },
      {
        "id": 1083,
        "name": "Steel plateskirt"
      },
      {
        "id": 1193,
        "name": "Steel kiteshield"
      }
    ]
  },
  {
    "setId": 20376,
    "setName": "Steel trimmed set (lg)",
    "pieces": [
      {
        "id": 20193,
        "name": "Steel full helm (t)"
      },
      {
        "id": 20184,
        "name": "Steel platebody (t)"
      },
      {
        "id": 20187,
        "name": "Steel platelegs (t)"
      },
      {
        "id": 20196,
        "name": "Steel kiteshield (t)"
      }
    ]
  },
  {
    "setId": 20379,
    "setName": "Steel trimmed set (sk)",
    "pieces": [
      {
        "id": 20193,
        "name": "Steel full helm (t)"
      },
      {
        "id": 20184,
        "name": "Steel platebody (t)"
      },
      {
        "id": 20190,
        "name": "Steel plateskirt (t)"
      },
      {
        "id": 20196,
        "name": "Steel kiteshield (t)"
      }
    ]
  },
  {
    "setId": 29424,
    "setName": "Sunfire fanatic armour set",
    "pieces": [
      {
        "id": 28933,
        "name": "Sunfire fanatic helm"
      },
      {
        "id": 28936,
        "name": "Sunfire fanatic cuirass"
      },
      {
        "id": 28939,
        "name": "Sunfire fanatic chausses"
      }
    ]
  },
  {
    "setId": 13066,
    "setName": "Super potion set",
    "pieces": [
      {
        "id": 2436,
        "name": "Super attack(4)"
      },
      {
        "id": 2440,
        "name": "Super strength(4)"
      },
      {
        "id": 2442,
        "name": "Super defence(4)"
      }
    ]
  },
  {
    "setId": 31160,
    "setName": "Swampbark armour set",
    "pieces": [
      {
        "id": 25398,
        "name": "Swampbark helm"
      },
      {
        "id": 25389,
        "name": "Swampbark body"
      },
      {
        "id": 25401,
        "name": "Swampbark legs"
      },
      {
        "id": 25392,
        "name": "Swampbark gauntlets"
      },
      {
        "id": 25395,
        "name": "Swampbark boots"
      }
    ]
  },
  {
    "setId": 12879,
    "setName": "Torag's armour set",
    "pieces": [
      {
        "id": 4745,
        "name": "Torag's helm"
      },
      {
        "id": 4749,
        "name": "Torag's platebody"
      },
      {
        "id": 4751,
        "name": "Torag's platelegs"
      },
      {
        "id": 4747,
        "name": "Torag's hammers"
      }
    ]
  },
  {
    "setId": 31145,
    "setName": "Torva armour set",
    "pieces": [
      {
        "id": 26382,
        "name": "Torva full helm"
      },
      {
        "id": 26384,
        "name": "Torva platebody"
      },
      {
        "id": 26386,
        "name": "Torva platelegs"
      }
    ]
  },
  {
    "setId": 25380,
    "setName": "Trailblazer relic hunter (t1) armour set",
    "pieces": [
      {
        "id": 25028,
        "name": "Trailblazer hood (t1)"
      },
      {
        "id": 25031,
        "name": "Trailblazer top (t1)"
      },
      {
        "id": 25034,
        "name": "Trailblazer trousers (t1)"
      },
      {
        "id": 25037,
        "name": "Trailblazer boots (t1)"
      }
    ]
  },
  {
    "setId": 25383,
    "setName": "Trailblazer relic hunter (t2) armour set",
    "pieces": [
      {
        "id": 25016,
        "name": "Trailblazer hood (t2)"
      },
      {
        "id": 25019,
        "name": "Trailblazer top (t2)"
      },
      {
        "id": 25022,
        "name": "Trailblazer trousers (t2)"
      },
      {
        "id": 25025,
        "name": "Trailblazer boots (t2)"
      }
    ]
  },
  {
    "setId": 25386,
    "setName": "Trailblazer relic hunter (t3) armour set",
    "pieces": [
      {
        "id": 25001,
        "name": "Trailblazer hood (t3)"
      },
      {
        "id": 25004,
        "name": "Trailblazer top (t3)"
      },
      {
        "id": 25007,
        "name": "Trailblazer trousers (t3)"
      },
      {
        "id": 25010,
        "name": "Trailblazer boots (t3)"
      }
    ]
  },
  {
    "setId": 28777,
    "setName": "Trailblazer reloaded relic hunter (t1) armour set",
    "pieces": [
      {
        "id": 28712,
        "name": "Trailblazer reloaded headband (t1)"
      },
      {
        "id": 28715,
        "name": "Trailblazer reloaded top (t1)"
      },
      {
        "id": 28718,
        "name": "Trailblazer reloaded trousers (t1)"
      },
      {
        "id": 28721,
        "name": "Trailblazer reloaded boots (t1)"
      }
    ]
  },
  {
    "setId": 28780,
    "setName": "Trailblazer reloaded relic hunter (t2) armour set",
    "pieces": [
      {
        "id": 28724,
        "name": "Trailblazer reloaded headband (t2)"
      },
      {
        "id": 28727,
        "name": "Trailblazer reloaded top (t2)"
      },
      {
        "id": 28730,
        "name": "Trailblazer reloaded trousers (t2)"
      },
      {
        "id": 28733,
        "name": "Trailblazer reloaded boots (t2)"
      }
    ]
  },
  {
    "setId": 28783,
    "setName": "Trailblazer reloaded relic hunter (t3) armour set",
    "pieces": [
      {
        "id": 28736,
        "name": "Trailblazer reloaded headband (t3)"
      },
      {
        "id": 28739,
        "name": "Trailblazer reloaded top (t3)"
      },
      {
        "id": 28742,
        "name": "Trailblazer reloaded trousers (t3)"
      },
      {
        "id": 28745,
        "name": "Trailblazer reloaded boots (t3)"
      }
    ]
  },
  {
    "setId": 24469,
    "setName": "Twisted relic hunter (t1) armour set",
    "pieces": [
      {
        "id": 24405,
        "name": "Twisted hat (t1)"
      },
      {
        "id": 24407,
        "name": "Twisted coat (t1)"
      },
      {
        "id": 24409,
        "name": "Twisted trousers (t1)"
      },
      {
        "id": 24411,
        "name": "Twisted boots (t1)"
      }
    ]
  },
  {
    "setId": 24472,
    "setName": "Twisted relic hunter (t2) armour set",
    "pieces": [
      {
        "id": 24397,
        "name": "Twisted hat (t2)"
      },
      {
        "id": 24399,
        "name": "Twisted coat (t2)"
      },
      {
        "id": 24401,
        "name": "Twisted trousers (t2)"
      },
      {
        "id": 24403,
        "name": "Twisted boots (t2)"
      }
    ]
  },
  {
    "setId": 24475,
    "setName": "Twisted relic hunter (t3) armour set",
    "pieces": [
      {
        "id": 24387,
        "name": "Twisted hat (t3)"
      },
      {
        "id": 24389,
        "name": "Twisted coat (t3)"
      },
      {
        "id": 24391,
        "name": "Twisted trousers (t3)"
      },
      {
        "id": 24393,
        "name": "Twisted boots (t3)"
      }
    ]
  },
  {
    "setId": 13151,
    "setName": "Unholy book page set",
    "pieces": [
      {
        "id": 3831,
        "name": "Zamorak page 1"
      },
      {
        "id": 3832,
        "name": "Zamorak page 2"
      },
      {
        "id": 3833,
        "name": "Zamorak page 3"
      },
      {
        "id": 3834,
        "name": "Zamorak page 4"
      }
    ]
  },
  {
    "setId": 12875,
    "setName": "Verac's armour set",
    "pieces": [
      {
        "id": 4753,
        "name": "Verac's helm"
      },
      {
        "id": 4757,
        "name": "Verac's brassard"
      },
      {
        "id": 4759,
        "name": "Verac's plateskirt"
      },
      {
        "id": 4755,
        "name": "Verac's flail"
      }
    ]
  },
  {
    "setId": 31148,
    "setName": "Virtus armour set",
    "pieces": [
      {
        "id": 26241,
        "name": "Virtus mask"
      },
      {
        "id": 26243,
        "name": "Virtus robe top"
      },
      {
        "id": 26245,
        "name": "Virtus robe bottom"
      }
    ]
  },
  {
    "setId": 13044,
    "setName": "Zamorak armour set (lg)",
    "pieces": [
      {
        "id": 2657,
        "name": "Zamorak full helm"
      },
      {
        "id": 2653,
        "name": "Zamorak platebody"
      },
      {
        "id": 2655,
        "name": "Zamorak platelegs"
      },
      {
        "id": 2659,
        "name": "Zamorak kiteshield"
      }
    ]
  },
  {
    "setId": 13046,
    "setName": "Zamorak armour set (sk)",
    "pieces": [
      {
        "id": 2657,
        "name": "Zamorak full helm"
      },
      {
        "id": 2653,
        "name": "Zamorak platebody"
      },
      {
        "id": 3478,
        "name": "Zamorak plateskirt"
      },
      {
        "id": 2659,
        "name": "Zamorak kiteshield"
      }
    ]
  },
  {
    "setId": 13161,
    "setName": "Zamorak dragonhide set",
    "pieces": [
      {
        "id": 10374,
        "name": "Zamorak coif"
      },
      {
        "id": 10370,
        "name": "Zamorak d'hide body"
      },
      {
        "id": 10372,
        "name": "Zamorak chaps"
      },
      {
        "id": 10368,
        "name": "Zamorak bracers"
      }
    ]
  }
];
